version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  nexus-repo:
    image: sonatype/nexus3:3.68.1
    container_name: nexus-repo
    restart: always
    env_file: .env
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
      - ./nexus-admin-password:/nexus-data/admin.password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
    mem_limit: 3g
    cpus: 1.5
    networks:
      - app_network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXUS_USERNAME: ${NEXUS_USERNAME}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
        NEXUS_URL: ${NEXUS_URL}
    container_name: spring-app
    restart: on-failure
    depends_on:
      - mysql-db
      - nexus-repo
    env_file: .env
    ports:
      - "8085:8085"
    networks:
      - app_network

volumes:
  mysql_data:
  nexus_data:

networks:
  app_network:
    driver: bridge
