apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: app-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: app-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          env:
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: "false"
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-storage
      volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: app-stack
spec:
  selector:
    app: nexus
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
